services:
  postgres:
    image: postgres:15-alpine
    container_name: meeplix_postgres
    environment:
      POSTGRES_DB: meeplix_db
      POSTGRES_USER: meeplix_user
      POSTGRES_PASSWORD: meeplix_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meeplix_user -d meeplix_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
