name: Deploy to Azure VM

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          RUNWARE_API_KEY: ${{ secrets.RUNWARE_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production
          PORT: 3000
          PUBLIC_API: meeplix.live
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH="$HOME/.bun/bin:$PATH"
            cd /home/azureuser/meeplix/
            git pull
            bun install
            # sudo docker compose up -d
            cd server && bun install
            bun build \
             	--compile \
             	--minify-whitespace \
             	--minify-syntax \
             	--target bun \
             	--outfile server \
             	./src/index.ts

            pkill server
            chmod +x server
            # --- IMPORTANT: Stop existing server process first ---
            if lsof -i :3000 -t > /dev/null 2>&1; then
                echo "Killing existing process on port 3000..."
                kill -9 $(lsof -ti :3000)
                sleep 2 # Give it a moment to release the port
            fi

            # Start the server and immediately disown it
            nohup ./server > stdout.log 2> stderr.log & disown

            cd ../client && bun install
            bun run build
            mkdir -p /var/www/hayshin.dev/html || true
            cp -r build/* /var/www/hayshin.dev/html/
            sudo systemctl restart nginx
