name: Deploy to Azure VM

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH="$HOME/.bun/bin:$PATH"
            cd /home/azureuser/narrari/
            git pull
            bun install
            cd server && bun install
            bun build \
             	--compile \
             	--minify-whitespace \
             	--minify-syntax \
             	--target bun \
             	--outfile server \
             	./src/index.ts

            pkill server
            chmod +x server
            nohup ./server &

            cd ../client && bun install
            bun run build
            mkdir -p /var/www/hayshin.dev/html || true
            chown -R ***:*** /var/www/hayshin.dev/html
            cp -r build/* /var/www/hayshin.dev/html/
            sudo systemctl restart nginx
